package com.heathen.hadeswatch.core.settings

object SettingsKeys {
    const val REDUCED_MOTION = "reduced_motion"
    const val HIGH_CONTRAST = "high_contrast"
    const val LARGE_TEXT = "large_text"
    const val OPEN_EXTERNAL_IN_BROWSER = "open_external_in_browser"
    const val TOOL_K0READER_ENABLED = "tool_k0reader_enabled"
    const val TOOL_ARES_ENABLED = "tool_ares_enabled"
    const val TOOL_FIELD_NOTES_ENABLED = "tool_field_notes_enabled"
    const val TOOL_GATEWAYS_ENABLED = "tool_gateways_enabled"
    const val TOOL_SIGNAL_READER_ENABLED = "tool_signal_reader_enabled"
    const val K0READER_USE_SDK = "k0reader_use_sdk"
    const val FIELD_NOTES_DRAFT = "field_notes_draft"
    const val GATEWAYS_DATA = "gateways_data"
    const val SIGNAL_SNIPPETS_DATA = "signal_snippets_data"
    const val K0READER_WPM = "k0reader_wpm"
    const val K0READER_CHUNK_SIZE = "k0reader_chunk_size"
    const val K0READER_FONT_SIZE = "k0reader_font_size"
    const val K0READER_FOCUS_MODE = "k0reader_focus_mode"
    const val K0READER_PUNCTUATION_PAUSE = "k0reader_punctuation_pause"
    const val K0READER_ORP_ENABLED = "k0reader_orp_enabled"
    const val K0READER_SAVE_SESSION = "k0reader_save_session"
    const val K0READER_LAST_TEXT = "k0reader_last_text"
}
